### ISSUE TITLE
users in the lightdm login screen

### ISSUE THREAD

**Issue by polarmutex** [wiltaylor/dotfiles#2]
I saw a todo about this, do you know why users are not showing up in the login screen? 

my user showes up when building from a configuration.nix but not from a flake, any pointers on where to debug this?

Thanks

**Comment by wiltaylor** [comment]
Yeah that is a good question. I have not been able to figure this one out for a long time.

From what I can tell though it appears to be caused by the Accounts Service daemon. On dbus when calling org.freedesktop.Accounts ListCachedUsers() its not returning any user accounts.

**Comment by wiltaylor** [comment]
I had a bit more of a play around with it and only way I was able to get my account to show up in ListCachedUsers was to change my default shell back to bash from zsh. Not really an ideal solution though.

**Comment by wiltaylor** [comment]
@polarmutex I figured it out.
Reason its not showing up is zsh isn't in /etc/shells file.

To get it in there just add this to your config:

```nix
  environment.shells = [ pkgs.zsh pkgs.bash ];
```

**Comment by polarmutex** [comment]
thanks for figuring this out
