### ISSUE TITLE
Request for Help

### ISSUE THREAD

**Issue by maydayv7** [wiltaylor/dotfiles#3]
Hi, I'm pretty new to Nix, and have recently started experimenting with Flakes. I am extremely thankful for your very informative YouTube videos and your dotfiles repo. My Flakes config is uploaded [here](https://github.com/maydayv7/dotfiles)

#### Issue
I have been using snippets of your code to port my config to Flakes, but for some reason `home-manager` doesn't seem to work. While building, no errors are given, but any new changes to the config do not get added, and the program `home-manager` as well as the service `home-manager-${username}` is not found

**Comment by maydayv7** [comment]
#### Additional Info
The system config files are located at `modules`, and user config files at `modules/user/`

**Comment by wiltaylor** [comment]
What command are you using to build the home manager config?

The following should be doing it:
```shell
     nix build .#homeManagerConfigurations.v7.activationPackage
      ./result/activate
```

What the above does is builds the nix derivation that contains your home manager config but it won't be applied to your system until you run the activate script it generates. The same thing happens with your nixos config but the install scripts wrap it for you.

**Comment by maydayv7** [comment]
Oh, thanks a lot! This solves it for me. But, is it possible to integrate this while invoking `nixos-rebuild`

**Comment by wiltaylor** [comment]
You can if you import home manager as a module into your NixOS Configuration. That way it will do them both at the same time.
Some info on how to do that here: https://nixos.wiki/wiki/Home_Manager

The way I worked around it for my config though is I created a script called sys that I use to handle it for me.
https://github.com/wiltaylor/dotfiles/blob/master/roles/core/scripts.nix

**Comment by maydayv7** [comment]
Thank you!

**Comment by wiltaylor** [comment]
No worries :)

**Comment by maydayv7** [comment]
Hi, I have gotten myself stuck into another problem (this doesn't seem to end ;)  
Is there any way that the `config` parameter be accessed from `lib/host.nix`, for example:
```
password = config.secrets.password
```

**Comment by maydayv7** [comment]
And just a thought, in order to create custom `nix` developer shells, you have defined a `lib/shell.nix` and configuration in `flake.nix` calling the `mkShell` function, and then run the shell using `nix develop .#shells.${name}`. Instead, the `devShells.${system}` output allows you to do just the same and run the shell using `nix develop .#{name}`

**Comment by wiltaylor** [comment]
Yeah that was an idea I had awhile back that I never really ended up using. I have a lot of workflows I want to keep separate from each other.

I am actually in the process of replacing them with what I call nix workspace instead. Which is basically nix flakes that hold environment that I can create a shell in or run programs from.

My main reasons for doing this are:
- I want to keep my base system small
- Not have to update all of my programs at once (great for packages that tend to break all the time like tor browser).
- Ability to setup different levels of isolation (none, isolated home or even some form of containers).
- Ability to run workspace on non nixos systems.
