### ISSUE TITLE
Extend /etc/nixos/configuration.nix rather than overwriting it entirely

### ISSUE THREAD

**Issue by zwhitchcox** [wiltaylor/dotfiles#6]
Is there any reason you wouldn't just extend `/etc/nixos/configuration.nix` like this:

```nix
{
  outputs = { self, nixpkgs }: {
    # replace 'joes-desktop' with your hostname here.
    nixosConfigurations.joes-desktop = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [ /etc/nixos/configuration.nix ];
    };
  };
}
```

 instead of creating a new configuration entirely?

My thinking is that you could just let the system take care of things like `hardware-configuration.nix`, and you only overwrite the things you need to which would make it more portable.

I'm just learning nix though and watched your YouTube videos, so I'm not sure if there is some reason not to do this.

**Comment by wiltaylor** [comment]
You would lose one of the main advantages of nix if you did it that way which is reproducible builds. Your basically relying on there being some config on the machine already.

I would rather have a single repository that i can load onto a machine from install media and just redeploy my machine back to the way it was previously.

Also i think the flake I have setup is pretty portable as I just have to put the machine settings for each system I am managing this way in the flake instead.

**Comment by zwhitchcox** [comment]
Ok, thank you for the information.
